{
  "id": "example-gridfinity",
  "name": "Gridfinity Box",
  "ownerId": "dafiiit",
  "files": {
    "code": "const {\n  draw,\n  drawRoundedRectangle,\n  drawCircle,\n  makeSolid,\n  assembleWire,\n  makeFace,\n  EdgeFinder,\n} = replicad;\n\nconst defaultParams = {\n  xSize: 2,\n  ySize: 1,\n  heigth: 0.5,\n  withMagnet: false,\n  withScrew: false,\n  magnetRadius: 3.25,\n  magnetHeight: 2,\n  screwRadius: 1.5,\n  keepFull: false,\n  wallThickness: 1.2,\n};\n\n// Gridfinity magic numbers\nconst SIZE = 42.0;\nconst CLEARANCE = 0.5;\nconst AXIS_CLEARANCE = (CLEARANCE * Math.sqrt(2)) / 4;\n\nconst CORNER_RADIUS = 4;\nconst TOP_FILLET = 0.6;\n\nconst SOCKET_HEIGHT = 5;\nconst SOCKET_SMALL_TAPER = 0.8;\nconst SOCKET_BIG_TAPER = 2.4;\nconst SOCKET_VERTICAL_PART =\n  SOCKET_HEIGHT - SOCKET_SMALL_TAPER - SOCKET_BIG_TAPER;\nconst SOCKET_TAPER_WIDTH = SOCKET_SMALL_TAPER + SOCKET_BIG_TAPER;\n\nconst socketProfile = (_, startPoint) => {\n  const full = draw([-CLEARANCE / 2, 0])\n    .vLine(-CLEARANCE / 2)\n    .lineTo([-SOCKET_BIG_TAPER, -SOCKET_BIG_TAPER])\n    .vLine(-SOCKET_VERTICAL_PART)\n    .line(-SOCKET_SMALL_TAPER, -SOCKET_SMALL_TAPER)\n    .done()\n    .translate(CLEARANCE / 2, 0);\n\n  return full.sketchOnPlane(\"XZ\", startPoint);\n};\n\nconst buildSocket = ({\n  magnetRadius = 3.25,\n  magnetHeight = 2,\n  screwRadius = 1.5,\n  withScrew = true,\n  withMagnet = true,\n} = {}) => {\n  const baseSocket = drawRoundedRectangle(\n    SIZE - CLEARANCE,\n    SIZE - CLEARANCE,\n    CORNER_RADIUS\n  ).sketchOnPlane();\n\n  const slotSide = baseSocket.sweepSketch(socketProfile, {\n    withContact: true,\n  });\n\n  let slot = makeSolid([\n    slotSide,\n    makeFace(\n      assembleWire(\n        new EdgeFinder().inPlane(\"XY\", -SOCKET_HEIGHT).find(slotSide)\n      )\n    ),\n    makeFace(assembleWire(new EdgeFinder().inPlane(\"XY\", 0).find(slotSide))),\n  ]);\n\n  if (withScrew || withMagnet) {\n    const magnetCutout = withMagnet\n      ? drawCircle(magnetRadius).sketchOnPlane().extrude(magnetHeight)\n      : null;\n    const screwCutout = withScrew\n      ? drawCircle(screwRadius).sketchOnPlane().extrude(SOCKET_HEIGHT)\n      : null;\n\n    const cutout =\n      magnetCutout && screwCutout\n        ? magnetCutout.fuse(screwCutout)\n        : magnetCutout || screwCutout;\n\n    slot = slot\n      .cut(cutout.clone().translate([-13, -13, -5]))\n      .cut(cutout.clone().translate([-13, 13, -5]))\n      .cut(cutout.clone().translate([13, 13, -5]))\n      .cut(cutout.clone().translate([13, -13, -5]));\n  }\n\n  return slot;\n};\n\nconst range = (i) => [...Array(i).keys()];\nconst cloneOnGrid = (\n  shape,\n  { xSteps = 1, ySteps = 1, span = 10, xSpan = null, ySpan = null }\n) => {\n  const xCorr = ((xSteps - 1) * (xSpan || span)) / 2;\n  const yCorr = ((ySteps - 1) * (ySpan || xSpan || span)) / 2;\n\n  const translations = range(xSteps).flatMap((i) => {\n    return range(ySteps).map((j) => [i * SIZE - xCorr, j * SIZE - yCorr, 0]);\n  });\n  return translations.map((translation) =>\n    shape.clone().translate(translation)\n  );\n};\n\nconst buildTopShape = ({\n  xSize,\n  ySize,\n  includeLip = true,\n  wallThickness = 1.2,\n}) => {\n  const topShape = (basePlane) => {\n    const sketcher = draw([-SOCKET_TAPER_WIDTH, 0])\n      .line(SOCKET_SMALL_TAPER, SOCKET_SMALL_TAPER)\n      .vLine(SOCKET_VERTICAL_PART)\n      .line(SOCKET_BIG_TAPER, SOCKET_BIG_TAPER);\n\n    if (includeLip) {\n      sketcher\n        .vLineTo(-(SOCKET_TAPER_WIDTH + wallThickness))\n        .lineTo([-SOCKET_TAPER_WIDTH, -wallThickness]);\n    } else {\n      sketcher.vLineTo(0);\n    }\n\n    const basicShape = sketcher.close();\n\n    const shiftedShape = basicShape\n      .translate(AXIS_CLEARANCE, -AXIS_CLEARANCE)\n      .intersect(\n        drawRoundedRectangle(10, 10).translate(-5, includeLip ? 0 : 5)\n      );\n\n    // We need to shave off the clearance\n    let topProfile = shiftedShape\n      .translate(CLEARANCE / 2, 0)\n      .intersect(drawRoundedRectangle(10, 10).translate(-5, 0));\n\n    if (includeLip) {\n      // We remove the wall if we add a lip\n      topProfile = topProfile.cut(\n        drawRoundedRectangle(1.2, 10).translate(-0.6, -5)\n      );\n    }\n\n    return topProfile.sketchOnPlane(basePlane);\n  };\n\n  const boxSketch = drawRoundedRectangle(\n    xSize * SIZE - CLEARANCE,\n    ySize * SIZE - CLEARANCE,\n    CORNER_RADIUS\n  ).sketchOnPlane();\n\n  return boxSketch\n    .sweepSketch(topShape, { withContact: true })\n    .fillet(TOP_FILLET, (e) =>\n      e.inBox(\n        [-xSize * SIZE, -ySize * SIZE, SOCKET_HEIGHT],\n        [xSize * SIZE, ySize * SIZE, SOCKET_HEIGHT - 1]\n      )\n    );\n};\n\nfunction main(\n  r,\n  {\n    xSize = 2,\n    ySize = 1,\n    heigth = 0.5,\n    keepFull = false,\n    wallThickness = 1.2,\n    withMagnet = false,\n    withScrew = false,\n    magnetRadius = 3.25,\n    magnetHeight = 2,\n    screwRadius = 1.5,\n  } = {}\n) {\n  const stdHeight = heigth * SIZE;\n\n  let box = drawRoundedRectangle(\n    xSize * SIZE - CLEARANCE,\n    ySize * SIZE - CLEARANCE,\n    CORNER_RADIUS\n  )\n    .sketchOnPlane()\n    .extrude(stdHeight);\n\n  if (!keepFull) {\n    box = box.shell(wallThickness, (f) => f.inPlane(\"XY\", stdHeight));\n  }\n\n  const top = buildTopShape({\n    xSize,\n    ySize,\n    includeLip: !keepFull,\n  }).translateZ(stdHeight);\n\n  const socket = buildSocket({\n    withMagnet,\n    withScrew,\n    magnetRadius,\n    magnetHeight,\n    screwRadius,\n  });\n\n  let base = null;\n  cloneOnGrid(socket, { xSteps: xSize, ySteps: ySize, span: SIZE }).forEach(\n    (movedSocket) => {\n      if (base) base = base.fuse(movedSocket, { optimisation: \"commonFace\" });\n      else base = movedSocket;\n    }\n  );\n  return base\n    .fuse(box, { optimisation: \"commonFace\" })\n    .fuse(top, { optimisation: \"commonFace\" });\n}"
  },
  "version": "1.0.0",
  "lastModified": 1769597949026,
  "tags": []
}